version: '3.7'

services:
  shortener:
    container_name: shortener
    image: ${DOCKER_REGISTRY-}shortener
    build:
      context: .
      dockerfile: shortener/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      ##- ASPNETCORE_URLS=https://+:443;https://+:8080
#      - AppSettings__ConnectionString=mongodb://localhost:27017
    ports:
      - "8082:8080"
    #  - "8084:443"
    #    depends_on:
    #      - mongodb
    volumes:
      - /Users/edrisym/desktop/RiderProjects/Edrisym.Shortener:/src

#  mongodb:
#    container_name: mongodb
#    image: mongo:latest
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=password
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
  



#  alertmanager:
#    image: prom/alertmanager:latest
#    container_name: alertmanager
#    volumes:
#      - ./alertmanager:/etc/alertmanager
#    command:
#      - '--config.file=/etc/alertmanager/alertmanager.yml'
#      - '--storage.path=/alertmanager'
#    ports:
#      - '9093:9093'